seed: &seed 22 # set experiment seed
timestep: &timestep 1.0  #20
horizon: &horizon 10 #10
logdir: /home/cameron/tells/logs/marl/drones1
notes: multi agent trainging, diff initialization, no curriculum, smallest initiallization 2

alg:
  type : sac
  lr : 0.0001 
  gamma: 0.99
  nenvs : 2
  cpu_envs: 5
  target_ent: 0.1
  batch: 256
  batch_size: 256
  buffer_size: 1000000
  learning_starts: 100000
  pi : [512, 512] # #[512,512,512] #[256, 256] #
  vf : [512, 512] # #[512,512,512] #[256, 256] #
  cl:
    ts_start: 500000
    ts_end: 2500000
    val_start: 0.0
    val_end: 1.0
  timesteps : 100000

env:
  scenario: 3_agent_drones
  max_episode_length: 400 #in seconds
  agent_list: ['agent0', 'agent1', 'agent2', 'target']
  learned_agent_list: ['agent0', 'agent1', 'agent2']
  env_kwargs:
    grid_size: 20
    num_goal_boxes: 5
    num_protectors: 3
    goal_box_spacing: 1.0
    goal_box_half_extents: [0.5, 0.5, 0.1]
    protection_radius: &protection_radius 1.1
    intrusion_radius: 0.5
    base_altitude: 0.5
    base_speed: 6.0
    speed_ratio: 0.6
  controller_kwargs:
    adversary_repulsion_radius: 0.75
    adversary_repulsion_gain: 1.0
    adversary_attraction_gain: 1.0
    adversary_replan_steps: 10
    protection_radius: *protection_radius
    target_response: 1.0
    follow_threshold: 0.35
    max_gap_factor: 1.05
    deadzone: 0.35
    altitude_deadzone: 0.15

sim:
  n: 3 #number of pursuit agents

policy_list: ['agent0'] #, 'agent1', 'agent2']
