lr: 0.00001
seed: 2
if_cuda: True
gamma: 0.5
log_dir: 'logs/belief/'
label: '0'
train_batch: 256
val_batch: 256
test_batch: 256
num_workers: 15
num_gpus: 1
model_name: 'drones_NN'
input_channels: 63
output_channels: 12
data_dir: 'data/'
data_name: 'drones_fully_obs_4'
lr_schedule: [200, 500, 1000, 2000, 3000]
epochs: 3000

#everythin rel to adversary
