lr: 0.000001
seed: 2
if_cuda: True
gamma: 0.5
log_dir: 'logs/belief/'
label: 'ppotest7'
train_batch: 256
val_batch: 256
test_batch: 256
num_workers: 15
num_gpus: 1
model_name: 'NN'
input_channels: 40
output_channels: 4
data_dir: 'data/'
data_name: 'ppotest1'
lr_schedule: []
epochs: 1000

#everythin rel to adversary