seed: &seed 22 # set experiment seed
timestep: &timestep 1.0  #20
horizon: &horizon 10 #10
logdir: /home/cameron/tells/logs/marl/fire_ext_longestt
notes: multi agent trainging, diff initialization, no curriculum, smallest initiallization 2

alg:
  type : ppo
  lr : 0.00003
  gamma: 0.99
  nenvs : 20
  cpu_envs: 2
  target_ent: 0.1
  batch: 4096
  batch_size: 256
  num_gpus: 0
  pi : [256, 256, 256]
  vf : [256, 256, 256]
  timesteps: 20000
  checkpoint_freq: 250
  minibatch_size: 512
  num_epochs: 3
  lambda: 0.95
  entropy_coeff: 0.0
  clip_param: 0.05
  vf_clip_param: 10.0
  grad_clip: 0.25
  pretrain:
    enabled: true
    episodes: 1200
    epochs: 40
    batch_size: 1024
    lr: 0.0005
    value_loss_coef: 0.02
    grad_clip: 1.0
    eval_runs: 90

env:
  scenario: fire_extinguish_env
  max_episode_length: 125 
  agent_list: ['agent0', 'agent1', 'agent2', 'agent3', 'target']
  learned_agent_list: ['agent0', 'agent1', 'agent2', 'agent3']
  noise:
    team: 0.0
    target: 0.0
  env_kwargs:
    warm_up_steps: 25
  reward_kwargs:
    extinguish_scale: 0.01
    green_scale: -1
    red_scale: 1.0
    lose_penalty: -500
    extinguish_reward: 500
    bc_scale: 0.5
    proximity_penalty: 5.0
    belief_dev_scale: 0.5
  belief_kwargs:
    max_speed: 1.0
    std_dev: 1.0
  controller_kwargs:
    deadzone: 0.1


sim:
  n: 3 #number of pursuit agents

policy_list: ['agent0'] #, 'agent1', 'agent2']