seed: &seed 22 # set experiment seed
timestep: &timestep 0.5  #20
horizon: &horizon 10 #10
logdir: /home/cameron/tells/logs/marl/test15
notes: single policy, large batch

alg:
  type : sac
  lr : 0.0001 
  gamma: 0.99
  nenvs : 10
  cpu_envs: 40
  target_ent: 0.1
  batch: 256
  batch_size: 256
  pi : [512, 512, 512]
  vf : [512, 512, 512]
  timesteps : 15000

env:
  scenario: 3_agent_predator_prey
  max_episode_length: 500
  agent_list: ['target', 'agent0', 'agent1', 'agent2']
  learned_agent_list: ['agent0', 'agent1', 'agent2']
  scenario_kwargs:
    base_speed: 1.0
    speed_ratio: 0.7

sim:
  n: 3 #number of pursuit agents

policy_list: ['agent0', 'agent1', 'agent2']